# This jobs runs every day 2 hours after the nightly job for React Native so we can verify how the nightly is behaving.
name: Check Nightlies

on:
  workflow_dispatch:
  # nightly build @ 4:15 AM UTC
  schedule:
    - cron: '15 4 * * *'

jobs:
  check-nightly:
    runs-on: ubuntu-latest
    if: github.repository == 'react-native-community/nightly-tests'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check nightly
        run: |
          TODAY=$(date "+%Y%m%d")
          echo "Checking nightly for $TODAY"
          NIGHTLY="$(npm view react-native | grep $TODAY)"
          if [[ -z $NIGHTLY ]]; then
            echo 'Nightly job failed.'
            exit 1
          else
            echo 'Nightly Worked, All Good!'
          fi

  test-libraries:
    uses: ./.github/workflows/test-libraries-on-nightlies.yml
    needs: check-nightly
    secrets:
      discord_webhook_url: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
      firebase_app_email: ${{ secrets.FIREBASE_APP_EMAIL }}
      firebase_app_pass: ${{ secrets.FIREBASE_APP_PASS }}
      firebase_app_projectname: ${{ secrets.FIREBASE_APP_PROJECTNAME }}
      firebase_app_apikey: ${{ secrets.FIREBASE_APP_APIKEY }}
