# This jobs runs every day 2 hours after the nightly job for React Native so we can verify how the nightly is behaving.
name: Check Nightlies

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'website/**'
      - '.github/workflows/deploy-website.yml'
      - '.github/workflows/pr-check-new-entries.yml'
  workflow_dispatch:
  # nightly build @ 4:15 AM UTC
  schedule:
    - cron: '15 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-nightly:
    runs-on: ubuntu-latest
    if: github.repository == 'react-native-community/nightly-tests'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check nightly
        run: |
          TODAY=$(date "+%Y%m%d")
          echo "Checking nightly for $TODAY"
          NIGHTLY="$(npm view react-native | grep $TODAY)"
          if [[ -z $NIGHTLY ]]; then
            echo 'Nightly job failed.'
            exit 1
          else
            echo 'Nightly Worked, All Good!'
          fi

  test-libraries:
    uses: ./.github/workflows/test-libraries-on-nightlies.yml
    needs: check-nightly
    secrets:
      discord_webhook_url: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
      firebase_app_email: ${{ secrets.FIREBASE_APP_EMAIL }}
      firebase_app_pass: ${{ secrets.FIREBASE_APP_PASS }}
      firebase_app_projectname: ${{ secrets.FIREBASE_APP_PROJECTNAME }}
      firebase_app_apikey: ${{ secrets.FIREBASE_APP_APIKEY }}

  test-hermes-v1-ios:
    uses: ./.github/workflows/test-hermes-v1-ios.yml
    needs: check-nightly

  test-hermes-v1-android:
    uses: ./.github/workflows/test-hermes-v1-android.yml
    needs: check-nightly

  collect-results:
    runs-on: ubuntu-latest
    needs: [test-libraries, test-hermes-v1-ios, test-hermes-v1-android]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore outcomes
        uses: actions/download-artifact@v4
        with:
          pattern: '*-outcome'
          path: /tmp
      - name: Collect failures
        uses: actions/github-script@v6
        env:
          FIREBASE_APP_EMAIL: ${{ secrets.firebase_app_email }}
          FIREBASE_APP_PASS: ${{ secrets.firebase_app_pass }}
          FIREBASE_APP_APIKEY: ${{ secrets.firebase_app_apikey }}
          FIREBASE_APP_PROJECTNAME: ${{ secrets.firebase_app_projectname }}
        with:
          script: |
            const {collectResults} = require('./.github/workflow-scripts/collectNightlyOutcomes.js');
            await collectResults('${{secrets.discord_webhook_url}}');