name: Deploy website

on:
  workflow_dispatch:
  # deploy daily @ 5:30 AM UTC
  schedule:
    - cron: '30 5 * * *'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: ‚öôÔ∏è Setup Node
        uses: actions/setup-node@v6
        with:
          cache: 'yarn'

      - name: üööÔ∏è Install dependencies
        working-directory: website
        run: yarn install --frozen-lockfile

      - name: ‚¨áÔ∏è Fetch the latest test results
        working-directory: website
        run: yarn data:fetch
        env:
          FIREBASE_APP_PROJECTNAME: ${{ secrets.FIREBASE_APP_PROJECTNAME }}
          FIREBASE_APP_SERVICE_KEY: ${{ secrets.FIREBASE_APP_SERVICE_KEY }}

      - name: üì¶Ô∏è Build website app
        working-directory: website
        run: yarn build
        env:
          REPOSITORY_NAME: 'nightly-tests'

      - name: üöÄ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out
